# Environment for Geometrodynamics of Entropy (GoE) v5.0 Core
name: goe-core
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - sympy>=1.8.0
  - pip
  - pip:
    - ipykernel
    - ipywidgets
