name: LaTeX CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'docs/*.tex', 'figures/**', 'references.bib' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/*.tex', 'figures/**', 'references.bib' ]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: docs/ctmck_article_v03.tex
        working_directory: .
        args: -pdf -interaction=nonstopmode -halt-on-error
        extra_system_packages: |
          py3-pygments
          
    - name: Check PDF generation
      run: |
        if [ -f "docs/ctmck_article_v03.pdf" ]; then
          echo "✓ PDF generated successfully"
          PDF_SIZE=$(wc -c < docs/ctmck_article_v03.pdf)
          echo "PDF size: ${PDF_SIZE} bytes"
          if [ "$PDF_SIZE" -lt 100000 ]; then
            echo "⚠ Warning: PDF size seems unusually small"
            exit 1
          fi
        else
          echo "✗ PDF generation failed"
          exit 1
        fi
    
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: ctmck-article-pdf
        path: docs/ctmck_article_v03.pdf
        retention-days: 30
    
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: latex-build-logs
        path: |
          *.log
          *.aux
          *.out
        retention-days: 7

  quality-check:
    runs-on: ubuntu-latest
    needs: build-latex
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
    
    - name: Run Python linting
      run: |
        echo "Running flake8..."
        find scripts/ -name "*.py" -exec flake8 {} \; || true
        echo "Checking code formatting..."
        find scripts/ -name "*.py" -exec black --check {} \; || true
    
    - name: Validate repository structure
      run: |
        echo "Checking repository structure..."
        required_files=("README.md" "LICENSE" "CITATION.cff" "references.bib" "docs/ctmck_article_v03.tex")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✓ $file found"
          else
            echo "✗ $file missing"
            exit 1
          fi
        done
        
        required_dirs=("docs" "figures" "scripts")
        for dir in "${required_dirs[@]}"; do
          if [ -d "$dir" ]; then
            echo "✓ $dir/ directory found"
          else
            echo "✗ $dir/ directory missing"
            exit 1
          fi
        done
